version: 2.1
orbs:
  ft-golang-ci: financial-times/golang-ci@1
jobs:
  build:
    working_directory: /go/src/github.com/Financial-Times/list-notifications-rw
    docker:
      - image: golang:1
        environment:
          GOPATH: /go
          MONGO_TEST_URL: localhost:27017
          CIRCLE_TEST_REPORTS: /tmp/test-results
          CIRCLE_COVERAGE_REPORT: /tmp/coverage-results
      - image: mongo:6.0.4
    steps:
      - checkout
      - ft-golang-ci/build
      - ft-golang-ci/lint
      - ft-golang-ci/test

workflows:
  test-and-build-docker:
    jobs:
      - build:
          name: build
          context: cm-team-github
      - ft-golang-ci/docker-build:
          name: build-docker-image
          requires:
            - build
          context: cm-team-github
  snyk-scanning:
    jobs:
      - ft-golang-ci/scan:
          name: scan-dependencies
          context:
            - cm-team-snyk
            - cm-team-github
