# Values used for the deployed application.
replicaCount: 2
service:
  name: list-notifications-rw
env:
  DUMP_REQUESTS: false
  DB_NAME: upp-store
  DB_COLLECTION: list-notifications
  NOTIFICATIONS_LIMIT: 200
