# Default values for list-notifications-rw.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
service:
  name: "" # The name of the service, should be defined in the specific app-configs folder.
  hasHealthcheck: "true"
replicaCount: 2
image:
  repository: coco/list-notifications-rw
  pullPolicy: IfNotPresent
resources:
  limits:
    memory: 128Mi
env:
  DUMP_REQUESTS: false
